wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.19.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687273146.440646
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 63
      3:
      - 7
      - 13
      - 23
      4: 3.8.10
      5: 0.15.4
      6: 4.19.2
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
